Controllers/BaseReportController.cs
using BusinessServiceFramework;
using BusinessServiceFramework.Models;
using DomainModelFramework;
using ReportingBusinessService;
using ReportingBusinessService.Models;
using ReportingDomainModel;
using ReportingResources;
using ReportingWeb.ActionFilters;
using ReportingWeb.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;

namespace ReportingWeb.Controllers
{
    public class BaseReportController : BaseAdminController
    {
        protected string FriendlyReportModuleName { get; set; }

        [AllowAnonymous]
        [HttpGet]
        public ContentResult GetReportMembers(string value, string selectedData)
        {
            UserService service = new UserService();
            List<FilterOption> filters = new List<FilterOption>();

            String jsonResult = null;

            try
            {
                if (!string.IsNullOrEmpty(selectedData))
                {
                    string[] selectedItemArray = selectedData.Split(",".ToCharArray());

                    foreach (string selectedItem in selectedItemArray)
                    {
                        long itemID = 0;

                        Int64.TryParse(selectedItem, out itemID);

                        FilterOption filterItemID = new FilterOption()
                        {

                            Label = new string[] { "UserID" },
                            Operator = FilterOperator.NotEqual,
                            Type = FilterType.Property,
                            Unison = FilterUnison.And,
                            Value = itemID
                        };

                        filters.Add(filterItemID);
                    }
                }

                FilterOption filterValue = new FilterOption()
                {

                    Label = new string[] { "FullName" },
                    Operator = FilterOperator.Like,
                    Type = FilterType.Custom,
                    Unison = FilterUnison.And,
                    Value = value
                };

                filters.Add(filterValue);

                FilterOption filterIsActive = new FilterOption()
                {

                    Label = new string[] { "IsActive" },
                    Operator = FilterOperator.Equal,
                    Type = FilterType.Property,
                    Unison = FilterUnison.And,
                    Value = true
                };

                filters.Add(filterIsActive);

                FilterOption filterIsMember = new FilterOption()
                {

                    Label = new string[] { "IsMember" },
                    Operator = FilterOperator.Equal,
                    Type = FilterType.Property,
                    Unison = FilterUnison.And,
                    Value = true
                };

                filters.Add(filterIsMember);

                IEnumerable<User> data = service.Get(filters);

                if (data.Count() > 0)
                {
                    data = data.Take(this.DeveloperSettings.AutoCompletePageSize);
                }

                var results = data.Select(x => new
                {
                    UserID = x.UserID,
                    Name = x.FullName,
                }).ToArray();

                JsonSerializerSettings settings = new JsonSerializerSettings();
                jsonResult = JsonConvert.SerializeObject(results, settings);
            }
            catch (Exception e)
            {
                throw e;
            }

            return this.Content(jsonResult, "application/json");
        }

        [AllowAnonymous]
        [HttpGet]
        public ContentResult GetReportProjects(string value, string selectedData)
        {
            ProjectService service = new ProjectService();
            List<FilterOption> filters = new List<FilterOption>();

            String jsonResult = null;

            try
            {
                if (!string.IsNullOrEmpty(selectedData))
                {
                    string[] selectedItemArray = selectedData.Split(",".ToCharArray());

                    foreach (string selectedItem in selectedItemArray)
                    {
                        long itemID = 0;

                        Int64.TryParse(selectedItem, out itemID);

                        FilterOption filterItemID = new FilterOption()
                        {

                            Label = new string[] { "ProjectID" },
                            Operator = FilterOperator.NotEqual,
                            Type = FilterType.Property,
                            Unison = FilterUnison.And,
                            Value = itemID
                        };

                        filters.Add(filterItemID);
                    }
                }

                FilterOption filterValue = new FilterOption()
                {

                    Label = new string[] { "Name" },
                    Operator = FilterOperator.Like,
                    Type = FilterType.Property,
                    Unison = FilterUnison.And,
                    Value = value
                };

                filters.Add(filterValue);

                FilterOption filterIsActive = new FilterOption()
                {

                    Label = new string[] { "IsActive" },
                    Operator = FilterOperator.Equal,
                    Type = FilterType.Property,
                    Unison = FilterUnison.And,
                    Value = true
                };

                filters.Add(filterIsActive);

                IEnumerable<Project> data = service.Get(filters);

                if (data.Count() > 0)
                {
                    data = data.Take(this.DeveloperSettings.AutoCompletePageSize);
                }

                var results = data.Select(x => new
                {
                    ProjectID = x.ProjectID,
                    Name = x.Name,
                }).ToArray();

                JsonSerializerSettings settings = new JsonSerializerSettings();
                jsonResult = JsonConvert.SerializeObject(results, settings);
            }
            catch (Exception e)
            {
                throw e;
            }

            return this.Content(jsonResult, "application/json");
        }

        [AllowAnonymous]
        [HttpGet]
        public ContentResult GetJobRoles(string value, string selectedData)
        {
            JobRoleService service = new JobRoleService();
            List<FilterOption> filters = new List<FilterOption>();

            String jsonResult = null;

            try
            {
                if (!string.IsNullOrEmpty(selectedData))
                {
                    string[] selectedItemArray = selectedData.Split(",".ToCharArray());

                    foreach (string selectedItem in selectedItemArray)
                    {
                        long itemID = 0;

                        Int64.TryParse(selectedItem, out itemID);

                        FilterOption filterItemID = new FilterOption()
                        {

                            Label = new string[] { "JobRoleID" },
                            Operator = FilterOperator.NotEqual,
                            Type = FilterType.Property,
                            Unison = FilterUnison.And,
                            Value = itemID
                        };

                        filters.Add(filterItemID);
                    }
                }

                FilterOption filterValue = new FilterOption()
                {

                    Label = new string[] { "Name" },
                    Operator = FilterOperator.Like,
                    Type = FilterType.Property,
                    Unison = FilterUnison.And,
                    Value = value
                };

                filters.Add(filterValue);

                FilterOption filterIsActive = new FilterOption()
                {

                    Label = new string[] { "Outlet.IsActive" },
                    Operator = FilterOperator.Equal,
                    Type = FilterType.Property,
                    Unison = FilterUnison.And,
                    Value = true
                };

                filters.Add(filterIsActive);

                IEnumerable<JobRole> data = service.Get(filters);

                if (data.Count() > 0)
                {
                    data = data.Take(this.DeveloperSettings.AutoCompletePageSize);
                }

                var results = data.Select(x => new
                {
                    ItemID = x.JobRoleID,
                    Name = x.Name,
                }).ToArray();

                JsonSerializerSettings settings = new JsonSerializerSettings();
                jsonResult = JsonConvert.SerializeObject(results, settings);
            }
            catch (Exception e)
            {
                throw e;
            }

            return this.Content(jsonResult, "application/json");
        }

        protected override IEnumerable<BreadcrumbItem> GetBreadcrumbItems()
        {
            List<BreadcrumbItem> items = new List<BreadcrumbItem>();
            items.Add(new BreadcrumbItem() { Text = FrameworkResources.Home, Link = this.GetDefaultReturnPage() });
            items.Add(new BreadcrumbItem() { Text = GeneralResources.Reports, Link = "Reports" });
            items.Add(new BreadcrumbItem() { Text = this.FriendlyReportModuleName, Link = "" });

            ViewBag.Breadcrumbs = items;

            return items;
        }

        protected override List<ListColumn> GetColumns()
        {
            return new List<ListColumn>();
        }

        protected FilterReportModel GenerateBaseFilterReportModel(DateTime? startDate, DateTime? endDate, string selectedUsers, string selectedProjects, bool isPrint, string type)
        {

Views/Shared/_AlertPartial.cshtml
<div>
    <div id="div-alert-success" class="alert alert-success @Html.Raw(string.IsNullOrEmpty(ViewBag.SuccessText) ? " hidden" : "" )">
        <span class="glyphicon glyphicon-ok"></span> @Html.Raw(ViewBag.SuccessText)
    </div>

    <div id="div-alert-info" class="alert alert-info @Html.Raw(string.IsNullOrEmpty(ViewBag.InfoText) ? " hidden" : "" )">
        <span class="glyphicon glyphicon-info-sign"></span> @Html.Raw(ViewBag.InfoText)
    </div>

    <div id="div-alert-error" class="alert alert-danger @Html.Raw(string.IsNullOrEmpty(ViewBag.ErrorText) ? " hidden" : "" )">
        <span class="glyphicon glyphicon-exclamation-sign"></span> @Html.Raw(ViewBag.ErrorText)
    </div>
</div>

Views/Shared/_ArticleActionsPartial.cshtml
@using CulinaryBizDomainModel
@using DomainModelFramework

@model Article

@{
    bool canEdit = (bool)ViewBag.CanEdit;
    bool canDelete = (bool)ViewBag.CanDelete;
}

<td class="list-icon">
    <a href="@Url.Action("View", new { id = Model.ArticleID })">
        <img src="@Url.Content("~/Images/view-normal.png")"
             onmouseover="this.src='@Url.Content("~/images/view-hover.png")'"
             onmouseout="this.src='@Url.Content("~/images/view-normal.png")'"
             alt="@FrameworkResources.View" title="@FrameworkResources.View" />
    </a>
    @if (Model.PublishedDate == null)
    {
        if (canEdit)
        {
            <a href="@Url.Action("Detail", new { id = Model.ArticleID })">
                <img src="@Url.Content("~/Images/edit-normal.png")" onmouseover="this.src='@Url.Content("~/images/edit-hover.png")'"
                     onmouseout="this.src='@Url.Content("~/images/edit-normal.png")'" alt="@FrameworkResources.Edit" title="@FrameworkResources.Edit" />
            </a>
        }
        if (canDelete)
        {
            <a>
                <img src="@Url.Content("~/Images/delete-normal.png")" onmouseover="this.src='@Url.Content("~/images/delete-hover.png")'" onclick="deleteItem(@Model.ArticleID, '@GeneralResources.Article')"
                     onmouseout="this.src='@Url.Content("~/images/delete-normal.png")'" alt="@FrameworkResources.Delete" title="@FrameworkResources.Delete" />
            </a>
        }
    }
</td>

Views/Shared/_BannerItemPartial.cshtml
@using ReportingBusinessService.Models
@using ReportingDomainModel
@using System.Collections.Generic
@using System.Linq
@using System.Globalization
@using System.Web.Script.Serialization
@using BusinessServiceFramework.Models

@model Navigation

@{
    string defaultLanguage = ViewBag.DefaultLanguage;
    string language = ViewBag.CurrentLanguage;
    Info store = (Info)ViewBag.Info;
    string baseUrl = string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~"));
}

@foreach (NavigationSection section in Model.Sections)
{
    <div id="banner-carousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner" role="listbox">
            @for (int i = 0; i < section.Items.Count(); i++)
            {
                NavigationItem item = section.Items[i];

                <div class="item @(i == 0 ? "active" : "")">
                    @if (item.DisplayMode == DomainModelFramework.DisplayMode.Image)
                    {
                        string path = Url.Content("~/Images/" + item.GetImage(language, defaultLanguage));
                        if (Request.Browser.IsMobileDevice)
                        {
                            path = path.Insert(path.IndexOf(".png"), "-mobile");
                        }

                        <a href="@Html.Raw(baseUrl+item.Link)">
                            <img src="@path" alt="banner reporting" />
                        </a>
                    }
                    else if (item.DisplayMode == DomainModelFramework.DisplayMode.Video)
                    {
                        string videoName = item.GetVideo(language, defaultLanguage);
                        string videoExt = videoName.Split(new string[] { "." }, StringSplitOptions.RemoveEmptyEntries).LastOrDefault();

                        <video loop="loop">
                            <source src="@Url.Content("~/Videos/" + videoName)" type="video/@videoExt" />
                            sorry; your browser doesn't support HTML5 video in WebM with VP8 or MP4 with H.264.
                        </video>
                    }
                </div>
            }
        </div>

        @if (section.Items.Count > 1)
        {
            @Html.Partial("_BannerPointerPartial")
        }
    </div>
}

Views/Shared/_BreadcrumbPartial.cshtml
@using BusinessServiceFramework.Models

@model IEnumerable<BreadcrumbItem>

<ol class="breadcrumb">

    @if (Model != null)
    {

        for (int i = 0; i < Model.Count(); i++)
        {
            BreadcrumbItem item = Model.ElementAt(i) as BreadcrumbItem;

            if (i == Model.Count() - 1)
            {
                <li class="active">@item.Text</li>
            }
            else
            {
                <li><a href="@item.Link">@item.Text</a></li>
            }
        }
    }
</ol>

Views/Shared/_DailyScrumActionPartial.cshtml
@using ReportingDomainModel
@using DomainModelFramework

@model DailyScrum

@{
    bool canEdit = (bool)ViewBag.CanEdit;
    bool canDelete = (bool)ViewBag.CanDelete;

    long modelID = Model.DailyScrumID;
}

<td class="list-icon">
    @if (!canEdit)
    {
        <a href="@Url.Action("View", new { id = modelID })">
            <img src="@Url.Content("~/Images/view-normal.png")"
                 onmouseover="this.src='@Url.Content("~/images/view-hover.png")'"
                 onmouseout="this.src='@Url.Content("~/images/view-normal.png")'"
                 alt="@FrameworkResources.View" title="@FrameworkResources.View" />
        </a>
    }
    @if (canEdit)
    {
        <a href="@Url.Action("Detail", new { id = modelID })">
            <img src="@Url.Content("~/Images/edit-normal.png")" onmouseover="this.src='@Url.Content("~/images/edit-hover.png")'"
                 onmouseout="this.src='@Url.Content("~/images/edit-normal.png")'" alt="@FrameworkResources.Edit" title="@FrameworkResources.Edit" />
        </a>
    }
    @if (canDelete)
    {
        <a>
            <img src="@Url.Content("~/Images/delete-normal.png")" onmouseover="this.src='@Url.Content("~/images/delete-hover.png")'" onclick="deleteItem(@modelID, '@GeneralResources.DailyScrum')"
                 onmouseout="this.src='@Url.Content("~/images/delete-normal.png")'" alt="@FrameworkResources.Delete" title="@FrameworkResources.Delete" />
        </a>
    }
</td>

Views/Shared/_JobRoleActionPartial.cshtml
@using ReportingDomainModel
@using DomainModelFramework

@model JobRole

@{
    bool canEdit = (bool)ViewBag.CanEdit;
    bool canDelete = (bool)ViewBag.CanDelete;

    long modelID = Model.JobRoleID;
}

<td class="list-icon">
    <a href="@Url.Action("View", new { id = modelID })">
        <img src="@Url.Content("~/Images/view-normal.png")"
             onmouseover="this.src='@Url.Content("~/images/view-hover.png")'"
             onmouseout="this.src='@Url.Content("~/images/view-normal.png")'"
             alt="@FrameworkResources.View" title="@FrameworkResources.View" />
    </a>
    @if (canEdit)
    {
        <a href="@Url.Action("Detail", new { id = modelID })">
            <img src="@Url.Content("~/Images/edit-normal.png")" onmouseover="this.src='@Url.Content("~/images/edit-hover.png")'"
                 onmouseout="this.src='@Url.Content("~/images/edit-normal.png")'" alt="@FrameworkResources.Edit" title="@FrameworkResources.Edit" />
        </a>
    }
    @if (canDelete)
    {
        <a>
            <img src="@Url.Content("~/Images/delete-normal.png")" onmouseover="this.src='@Url.Content("~/images/delete-hover.png")'" onclick="deleteItem(@modelID, '@Model.Name.ToString()')"
                 onmouseout="this.src='@Url.Content("~/images/delete-normal.png")'" alt="@FrameworkResources.Delete" title="@FrameworkResources.Delete" />
        </a>
    }
</td>

Views/Shared/_LanguageDefaultPartial.cshtml
@using JadeInventoryDomainModel
@using DomainModelFramework

@model Language

<td class="default-col">
    @if (Model.IsDefault)
    {
        <img title="@FrameworkResources.Default" class="img-responsive icon-uploaded default" src="@Url.Content("~/Images/default-language.png?" + DateTime.Now.ToString("ddyyhhmmss"))" alt="@FrameworkResources.Default">
    }
</td>

Views/Shared/_ListItemPartial.cshtml
@using DomainModelFramework
@using ReportingWeb.Models
@using System.Reflection
@using System.Globalization
@using System.Linq
@using System.Collections.Generic

@model BaseEntity

@{
    Type type = Type.GetType(ViewBag.EntityType);
    string keyValue = ViewBag.KeyPropertyInfo != null ? ViewBag.KeyPropertyInfo.GetValue(Model, null).ToString() : "";
   Dictionary<bool, string> subData= new Dictionary<bool, string>();

   if (ViewBag.SubData!=null)
   {
       subData = (Dictionary<bool, string>)ViewBag.SubData;
   }
}

<tr @(ViewBag.KeyPropertyInfo != null ? "itemID=" + keyValue : "'")>
    @foreach (ListColumn column in ViewBag.Columns)
    {
        string value = "";

        if (!string.IsNullOrEmpty(column.TextPropertyName))
        {
            object obj = Model;
            Type objType = type;

            foreach (string name in column.TextPropertyName.Split(new char[] { '.' }))
            {
                PropertyInfo info = objType.GetProperty(name);

                if (info != null)
                {
                    obj = info.GetValue(obj, null);
                    objType = info.PropertyType;
                }
                else
                {
                    break;
                }
            }

            if (obj is System.DateTime)
            {
                value = DateTime.Parse(obj.ToString()).ToString(ViewBag.DeveloperSettings.ShortDateFormat);
            }
            else if (obj is decimal)
            {
                value = decimal.Parse(obj.ToString()).ToString("N0");
            }
            else
            {
                if (obj != null)
                {
                    value = obj.ToString();
                }
            }
        }
        else
        {
            value = column.Text;
        }

        switch (column.DisplayMode)
        {
            case ListColumnDisplayMode.Checkbox:
            case ListColumnDisplayMode.CheckboxWithSelectAll:
                if (!string.IsNullOrEmpty(keyValue))
                {
                    <td>
                        @Html.CheckBox("checkbox-item-" + keyValue)
                    </td>
                }
                break;

            case ListColumnDisplayMode.Custom:
            @Html.Partial(@column.CustomPartialName, Model)
                break;

            case ListColumnDisplayMode.Text:
            default:
            <td>
                @Html.Raw(string.IsNullOrEmpty(value) ? "-" : value)
            </td>
                break;

            case ListColumnDisplayMode.Image:
            <td>
                <img src="@Url.Content("~/Images/" + value)" />
            </td>
                break;
        }
    }
</tr>

@if (subData.FirstOrDefault().Key)
{
    if (!string.IsNullOrEmpty(subData.FirstOrDefault().Value))
    {
        @Html.Partial(subData.FirstOrDefault().Value, Model)
    }
}

Views/Shared/_ProjectMultiselectFilterPartial.cshtml
@using DomainModelFramework

<script type="text/javascript">
    var url_get_projects = '@Url.Action("GetReportProjects", "BaseReport")';
</script>

<select id="project-dropdown" data-placeholder="@string.Format(FrameworkResources.TypeFormat,GeneralResources.Project)" multiple class="chosen-select"></select>

Views/Shared/_ProjectTaskMemberActionPartial.cshtml
@using ReportingDomainModel
@using DomainModelFramework

@model ProjectTaskMember

@{
    bool canEdit = (bool)ViewBag.CanEdit;
    bool canDelete = (bool)ViewBag.CanDelete;
    bool canApprove = Model.Status != ProjectTaskMemberStatus.APPROVED.ToString();
    bool canReject = Model.Status != ProjectTaskMemberStatus.REJECTED.ToString();

    long modelID = Model.ProjectTaskMemberID;
}

<td class="list-icon">
    @if (canApprove)
    {
        <a class="button_approve" id="@modelID">
            @GeneralResources.Approve
        </a>

        if (canReject)
        {
            <label>/</label>
        }
    }
    @if (canReject)
    {
        <a class="button_reject" id="@modelID">
            @GeneralResources.Reject
        </a>
    }
    @if (!canEdit)
    {
        <a href="@Url.Action("View", new { id = modelID })">
            <img src="@Url.Content("~/Images/view-normal.png")"
                 onmouseover="this.src='@Url.Content("~/images/view-hover.png")'"
                 onmouseout="this.src='@Url.Content("~/images/view-normal.png")'"
                 alt="@FrameworkResources.View" title="@FrameworkResources.View" />
        </a>
    }
    @if (canEdit)
    {
        <a href="@Url.Action("Detail", new { id = modelID })">
            <img src="@Url.Content("~/Images/edit-normal.png")" onmouseover="this.src='@Url.Content("~/images/edit-hover.png")'"
                 onmouseout="this.src='@Url.Content("~/images/edit-normal.png")'" alt="@FrameworkResources.Edit" title="@FrameworkResources.Edit" />
        </a>
    }
    @if (canDelete)
    {
        <a>
            <img src="@Url.Content("~/Images/delete-normal.png")" onmouseover="this.src='@Url.Content("~/images/delete-hover.png")'" onclick="deleteItem(@modelID, '@GeneralResources.ProjectTaskMember')"
                 onmouseout="this.src='@Url.Content("~/images/delete-normal.png")'" alt="@FrameworkResources.Delete" title="@FrameworkResources.Delete" />
        </a>
    }
</td>

Views/Shared/_ProjectTaskMemberDetailListPartial.cshtml
@using ReportingDomainModel

@model ProjectTaskMemberDetail

@{
    var item = Model;

    bool canEdit = (bool)ViewData["CanEdit"];
    IEnumerable<StatusTask> statusTasks = ViewData["StatusTasks"] as IEnumerable<StatusTask>;
    string indexData = ViewData["IndexData"].ToString();

    var controlName = "ProjectTaskMemberDetails[" + indexData + "]";
}

<tr name="row-@indexData" indexData="@indexData">

    @Html.Hidden(controlName + ".ProjectTaskID", item.ProjectTaskID)

    @if (canEdit)
    {
        <td class="table-content">
            <input name="select_selected_task" type="checkbox" value="@indexData" indexData="@indexData" />
            @Html.Hidden("ProjectTaskMemberDetails.Index", indexData)
            @Html.Hidden(controlName + ".CreatedBy", item.CreatedBy)
            @Html.Hidden(controlName + ".CreatedDate", item.CreatedDate)
            @Html.Hidden(controlName + ".ModifiedBy", item.ModifiedBy)
            @Html.Hidden(controlName + ".ModifiedDate", item.ModifiedDate)
            @Html.Hidden(controlName + ".ProjectTaskMemberID", item.ProjectTaskMemberID)
            @Html.Hidden(controlName + ".ProjectTaskMemberDetailID", item.ProjectTaskMemberDetailID)
        </td>
        <td class="table-content">
            @{
                var spanName = controlName + ".ProjectName";
            }
            <label name="@spanName">@item.ProjectName</label>
        </td>
        <td class="table-content">
            @Html.TextArea(controlName + ".ProjectTaskName", item.ProjectTaskName, new { @class = "form-control projecttaskdropdown", indexData = indexData })
        </td>
        <td class="table-content">
            @Html.TextArea(controlName + ".Description", item.Description, new { @class = "form-control descriptiondropdown", indexData = indexData })
        </td>
        <td class="table-content">
            @Html.DropDownList(controlName + ".StatusTaskID", new SelectList(statusTasks, "StatusTaskID", "Name", item.StatusTaskID), new { @class = "form-control" })
        </td>
        <td class="table-content">
            @Html.TextBox(controlName + ".Duration", item.Duration.ToString("N2"), new { @class = "form-control", mode = "decimal", numval = item.Duration.ToString("N2") })
        </td>
        <td class="table-content">
            @Html.TextArea(controlName + ".Notes", item.Notes, new { @class = "form-control" })
        </td>
    }
    else
    {
        <td class="table-content">
            <span>@item.ProjectName</span>
        </td>
        <td class="table-content">
            <span>@item.ProjectTaskName</span>
        </td>
        <td class="table-content">
            <span>@item.Description</span>
        </td>
        <td class="table-content">
            <span>@item.StatusTask.Name</span>
        </td>
        <td class="table-content">
            <label class="control-label">@item.Duration.ToString("N2")</label>
        </td>
        <td class="table-content">
            <span>@item.Notes</span>
        </td>
    }
</tr>

Views/Shared/_ReportFilterButtonsPartial.cshtml
@using DomainModelFramework

<div class="div-search-button text-center">
    <button type="button" class="btn btn-primary loader" id="button-preview">
        <span class="glyphicon glyphicon-search"></span> @FrameworkResources.Preview
    </button>
    <button type="button" class="btn btn-primary loader" id="button-print">
        <span class="glyphicon glyphicon-print"></span> @FrameworkResources.Print
    </button>
    <button type="button" class="btn btn-default loader" id="button-reset-report">
        <span class="glyphicon glyphicon-refresh"></span> @FrameworkResources.Reset
    </button>
</div>

Views/Shared/_UserMultiSelectFilterPartial.cshtml
@using DomainModelFramework

<script type="text/javascript">
    var url_get_users = '@Url.Action("GetReportMembers", "BaseReport")';
</script>

<select id="user-dropdown" data-placeholder="@string.Format(FrameworkResources.TypeFormat,GeneralResources.User)" multiple class="chosen-select"></select>